server:
  port: 8081
  servlet:
    context-path: user-transfer-api

spring:
  application:
    name: user-transfer-api

  r2dbc:
    url: r2dbc:postgres://localhost:5432/user_transfer_db
    username: postgres
    password: Vincere7

  sql:
    init:
      schema-locations: optional:schema/schema.sql
      mode: always

  kafka:
    bootstrap-servers: "localhost:9092"